name: Run TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run TestNG tests
        run: mvn clean test -DsuiteXmlFile=testng.xml
      - name: Run TestNG tests1
        run: mvn clean test -DsuiteXmlFile=testngGrid1.xml -DgridURL=http://localhost:4444/wd/hub -Dbrowser1=chrome -Dbrowser2=firefox
